//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZBudget.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Monthly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category_Monthly()
        {
            this.Expenses = new HashSet<Expense>();
        }
    
        public int CategoryMonthlyID { get; set; }
        public Nullable<int> CategoryGlobalID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModifDate { get; set; }
    
        public virtual Category_Global Category_Global { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expense> Expenses { get; set; }
    }
}
