//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZBudget.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Global
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category_Global()
        {
            this.Category_Monthly = new HashSet<Category_Monthly>();
        }
    
        public int CategoryGlobalID { get; set; }
        public Nullable<int> BudgetID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public string ColorTag { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Budget Budget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_Monthly> Category_Monthly { get; set; }
    }
}
