//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZBudget.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseID { get; set; }
        public Nullable<int> CategoryMonthlyID { get; set; }
        public string ExpenseName { get; set; }
        public string ExpenseDescription { get; set; }
        public decimal Amount { get; set; }
        public string ExpenseBillImageUrl { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModifDate { get; set; }
    
        public virtual Category_Monthly Category_Monthly { get; set; }
    }
}
